### ISSUE TITLE
Yaml separator fix

### ISSUE THREAD

**Issue by massaox** [openanalytics/shinyproxy-operator#11]
Hi there.  I was working on a demo of the shinyproxy operator for a client and noticed a minor type in one of the yaml files `docs/deployment/clustered/shinyproxy2.yaml`.

Looks like the separator was added in the wrong  place:
```
...
roleRef:
  kind: Role
  name: shinyproxy-apps-role
  apiGroup: rbac.authorization.k8s.io
apiVersion: openanalytics.eu/v1alpha1
---
kind: ShinyProxy
metadata:
  name: example-shinyproxy
  namespace: yanamespace
...
```

The `apiVersion` for the Shinyproxy ended up in the `roleBinding` object. It should be:
```
...
roleRef:
  kind: Role
  name: shinyproxy-apps-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: openanalytics.eu/v1alpha1
kind: ShinyProxy
metadata:
  name: example-shinyproxy
  namespace: yanamespace
...
```

Seems like this operator has potential, however I was not able to get it working yet. Seems like the shinyproxy Pod couldn't create the app Pods, but I digress....
