### ISSUE TITLE
Liveness and Readiness probe errors for ShinyProxy deployment

### ISSUE THREAD

**Issue by cnukwas** [openanalytics/shinyproxy-operator#2]
Deployed ShinyProxy Operator as is and noticed that ShinyProxy pod going into CrashLoopBackOff status due to liveness and readiness probe errors. I don't see mention of these probes anywhere either in the crd.yaml or shinyproxy.yaml, so not sure where these are configured. Is there a way to configure or disable these probes?

Note that I did not run any YAML files related Skipper-Ingress since we want to use our own Ingress Controller. I don't think it's related to that but making a note of that.

```
Warning  Unhealthy  36s (x6 over 44s)  kubelet, mynode04  Liveness probe failed: Get http://192.168.222.152:8080/actuator/health/liveness: dial tcp 192.168.222.152:8080: connect: connection refused
Warning  Unhealthy  36s (x5 over 43s)  kubelet, mynode04  Readiness probe failed: Get http://192.168.222.152:8080/actuator/health/readiness: dial tcp 192.168.222.152:8080: connect: connection refused
Normal   Killing    36s (x2 over 42s)  kubelet, mynode04  Container shinyproxy failed liveness probe, will be restarted
```

**Comment by cnukwas** [comment]
Tried to replace or change but none of the attempts have worked, so added below YAML under kubernetesPodTemplateSpecPatches section, to temporarily disable the probes, until a root cause is found.

```
- op: remove
   path: /spec/containers/0/readinessProbe
- op: remove
   path: /spec/containers/0/livenessProbe
```

**Comment by LEDfan** [comment]
In our configurations, the liveness and readiness probes are working correctly, but only if you are using a Kubernetes version which supports StartupProbes, otherwise you will see similar behavior as you pointed out.

For deployments running older Kubernetes version (e.g. 1.17) we use the following configuration with success:
```
  kubernetesPodTemplateSpecPatches: |
    - op: replace
      path: /spec/containers/0/livenessProbe
      value:
        failureThreshold: 2
        httpGet:
          path: /actuator/health/liveness
          port: 8080
          scheme: HTTP
        periodSeconds: 1
        initialDelaySeconds: 140
        successThreshold: 1
        timeoutSeconds: 1
    - op: replace
      path: /spec/containers/0/readinessProbe
      value:
        failureThreshold: 2
        httpGet:
          path: /actuator/health/readiness
          port: 8080
          scheme: HTTP
        periodSeconds: 1
        initialDelaySeconds: 140
        successThreshold: 1
        timeoutSeconds: 1
```
