### ISSUE TITLE
ShinyProxy not able to start with SAML settings

### ISSUE THREAD

**Issue by templary** [openanalytics/shinyproxy-operator#24]
Hello,

When implementing the ShinyProxy oprator we encountered a problem, even if I use the original unmodified version of shinyproxy it does not work if I put it in the settings to auth mode: SAML 

The application runs in a kubernetes cluster on Gcloud

.yaml config file

```
apiVersion: openanalytics.eu/v1
kind: ShinyProxy
metadata:
  name: shinyproxy
  namespace: shinyproxy
spec:
  server:
    secureCookies: true
    frameOptions: sameorigin
    forward-headers-strategy: native
  spring:
    session:
      store-type: redis
      redis:
        configure-action: none
    redis:
      host: redis
      password: ${REDIS_PASSWORD}
  proxy:
    operator:
      force-transfer: true
    title: ShinyProxy_222
    logoUrl: ""
    landingPage: /
    containerBackend: kubernetes
    kubernetes:
      namespace: shinyproxy
      internal-networking: true
      image-pull-policy: Always
    authentication: saml
    saml:
      idp-metadata-url: https://XXXXX.eu.auth0.com/samlp/metadata/XXXXXX
      app-entity-id: urn:XXXX
      app-base-url: http://localhost:8080
      name-attribute: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
      roles-attribute: http://schemas.auth0.com/roles
      logout-url: https://XXXXX/v2/logout?client_id=XXXXXX&returnTo=http://localhost:8080
      nameidentifier-attribute: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier
      email-verified-attribute: http://schemas.auth0.com/email_verified
      created-at-attribute: http://schemas.auth0.com/created_at
    admin-groups: scientists
    users:
      - name: jack
        password: password
        groups: scientists
      - name: jeff
        password: password
        groups: mathematicians
    specs:
      - id: 01_hello
        display-name: Hello Application
        description: Application which demonstrates the basics of a Shiny app
        container-cmd: [ "R", "-e", "shinyproxy::run_01_hello()" ]
        container-image: openanalytics/shinyproxy-demo
        access-groups: [ scientists, mathematicians ]
      - id: 06_tabsets
        container-cmd: [ "R", "-e", "shinyproxy::run_06_tabsets()" ]
        container-image: openanalytics/shinyproxy-demo
        access-groups: scientists
      - id: rstudio
        displayName: RStudio
        description: RStudio
        containerImage: openanalytics/shinyproxy-rstudio-ide-demo:1.4.1106__4.0.4
        port: 8787
        container-env:
          DISABLE_AUTH: true
          WWW_ROOT_PATH: "#{proxySpec.containerSpecs[0].env.get('SHINYPROXY_PUBLIC_PATH')}"
  kubernetesPodTemplateSpecPatches: |
    - op: add
      path: /spec/containers/0/env/-
      value:
        name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: redis-password
            key: password
    - op: add
      path: /spec/containers/0/resources
      value:
        limits:
          cpu: 1
        requests:
          cpu: 0.5
    - op: add
      path: /spec/serviceAccountName
      value: shinyproxy-sa
    - op: replace
      path: /spec/containers/0/startupProbe
      value:
        httpGet:
          path: /actuator/health/liveness
          port: 9090
          scheme: HTTP
        timeoutSeconds: 3
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 6
        initialDelaySeconds: 60
  image: openanalytics/shinyproxy:2.6.0
  imagePullPolicy: Always
  fqdn: shinyproxy-demo.local
```

Thank you a lot for your time
