### ISSUE TITLE
How to build custom shinyproxy-operator image?

### ISSUE THREAD

**Issue by cnukwas** [openanalytics/shinyproxy-operator#3]
I was able to set up and run shinyproxy-operator as is and noticed that the operator is using below container image. I see the image at [dockerhub](https://hub.docker.com/r/openanalytics/shinyproxy-operator-snapshot), is it possible to get either the source code or Dockerfile to know what goes into the image and tweak few things?
We would like to build our own image and use internal private registry for security reasons, to make sure that we know what's in the image.

````
spec:
      containers:
        - name: shinyproxy-operator
          image: openanalytics/shinyproxy-operator-snapshot:0.0.1-SNAPSHOT-20201005.090146
          imagePullPolicy: Always
          env:
            - name: SPO_MODE
              value: namespaced
      serviceAccountName: shinyproxy-operator-sa
````
