### ISSUE TITLE
Redis connection timeout

### ISSUE THREAD

**Issue by russellkemmit** [openanalytics/shinyproxy-operator#36]
Within the last 10 days, we have been experiencing issues connecting to Redis on GCP. Our setup has been working for months and randomly stopped working. Below is how I connect to Redis, FYI, this has not changed in months! I have manually connected to the Redis server using Python and I was able to connect successfully. Any help would be greatly appreciated!

I have tried switching from image openanalytics/shinyproxy-operator:1.0.0 to openanalytics/shinyproxy-operator:1.0.3 and that did not seem to help.

```yaml
 spring:
    redis:
      host: redis_host
      password: password
    session:
      redis:
        configure-action: none
      store-type: redis
```
