### ISSUE TITLE
Setting a "node-selector" parameter per application 

### ISSUE THREAD

**Issue by asmelterktx** [openanalytics/shinyproxy-operator#56]
Hi, 

I had a question if it is possible for kubernetes deployment backend to set "node-selector" parameter for each application separately instead of specifying it globally `proxy.kubernetes.node-selector`. For example, if application does not require GPU it will be placed on general CPU instance and if application requires GPU it will be placed on GPU instance?

Thank you.

**Comment by LEDfan** [comment]
Hi, currently ShinyProxy does not provide a dedicated property for this, but it's definitely possible using kubernetes pod patches, see https://shinyproxy.io/documentation/configuration/#kubernetes-1

For example:

```yaml
id: test
container-image: openanalytics/shinyproxy-demo
kubernetes-pod-patches:
- op: add
  path: /spec/nodeSelector
  value:
    myLabel: myValue
- op: add
  path: /spec/tolerations
  value:
    - key: "openanalytics.eu/dynamic-workload"
      operator: "Exists"
      effect: "NoSchedule"
```
