### ISSUE TITLE
How to have custom environment variables forwarded to ShinyProxy ?

### ISSUE THREAD

**Issue by marandet** [openanalytics/shinyproxy-operator#59]
Hello,

Thanks a lot for you great work with ShinyProxy and this Kubernetes Operator.

The documentation of ShinyProxy says that it is possible to fill some configurations keys with environment variables
https://www.shinyproxy.io/documentation/configuration/#config-env-var 

This is usefull for many usecases, but I can't figure out how to acheive this with the Operator ?

My usecase would be to get the configuration of many fields out of the application.yaml files, with a particular consideration for the `spec.proxy.openid.client-secret` field.
So I would like to be able to set the `PROXY_OPENID_CLIENT_SECRET` environment variables of each of my shinyproxy instances.

This is because I don't want to have theses fields versioned in my Git repositories, nor being spread within my CI/CD pipelines.

The best option for me would be to use a real secret, and inject-it whitin the shinyproxy deployement, but as this deployment is handled by the Operator I can't figure out how to acheive this.

Maybe by adding extra code in the `PodTemplateSpecFactory.tk` and with the shinyproxy-operator.yaml file with an envFrom attribute ?
Or is there any other options ?

**Comment by marandet** [comment]
Maybe something like this would be nice if one want to forward specific environment variables from the Operator to the ShinyProxy instances ?
( I am not a Kotlin developper, this is a suggestion from an IA assistant )

![Image](https://github.com/user-attachments/assets/39a856c6-922b-4947-81e8-1c4d1e071cf7)

``` 
                       .withEnv(listOf(
                            EnvVarBuilder()
                                .withName("SP_KUBE_POD_NAME")
                                .withNewValueFrom()
                                    .withNewFieldRef()
                                        .withFieldPath("metadata.name")
                                    .endFieldRef()
                                .endValueFrom()
                            .build(),
                            EnvVarBuilder()
                                .withName("SP_KUBE_POD_UID")
                                .withNewValueFrom()
                                    .withNewFieldRef()
                                        .withFieldPath("metadata.uid")
                                    .endFieldRef()
                                .endValueFrom()
                            .build(),
                            EnvVarBuilder()
                                .withName("PROXY_REALM_ID")
                                .withValue(shinyProxy.realmId)
                            .build(),
                            EnvVarBuilder()
                                .withName("PROXY_VERSION")
                                .withValue(version.toString())
                            .build()
                        ) + System.getenv().filterKeys { it.startsWith("PROXY_") }.map { (key, value) ->
                            EnvVarBuilder()
                                .withName(key)
                                .withValue(value)
                                .build()
                        })
```

**Comment by LEDfan** [comment]
Hi, happy to hear you like ShinyProxy! 
The operator does not provide a specific configuration option to set environment variables. However, it's possible to add JSON patches, which allows to fully customize the ShinyProxy pods. See https://github.com/openanalytics/shinyproxy-operator/tree/master/docs/deployment#modify-the-shinyproxy-pod This includes an example for setting an environment variable from a secret.

**Comment by marandet** [comment]
Hi, thanks a lot for your quick reply

Oh yes your are right, I didn't realise that the application.yaml file could also patch itself in order to fill his own values.
This is a kinda recursive self management
And yeah, thanks to this approach it is possible to set environment variables that are provided by other Kubernetes resources.

Here is the approach I used successfully, with 2 other resources files ; a configMap with my environment variables, and a secret file with the openID secret.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: openidsecret
type: Opaque
stringData:
  PROXY_OPENID_CLIENT_SECRET: <my-super-secret>
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: envconfigmap
data:
  #spec.proxy.openid.auth-url
  PROXY_OPENID_AUTH_URL: https://authorize-endpoint
  #spec.proxy.openid.jwks-url
  PROXY_OPENID_JWKS_URL: https://jwks-endpoint
  #spec.proxy.openid.userinfo-url
  PROXY_OPENID_USERINFO_URL: https://profile-endpoint
  #spec.proxy.openid.token-url
  PROXY_OPENID_TOKEN_URL: https://token-endpoint
  #spec.proxy.openid.client-id
  PROXY_OPENID_CLIENT_ID: <client-id>
  #spec.proxy.openid.username-claim
  PROXY_OPENID_USERNAME_CLAIM: <claim>
```


```yaml

  kubernetesPodTemplateSpecPatches: |
    - op: add
      path: /spec/containers/0/env
      value:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
        - name: PROXY_OPENID_AUTH_URL
          valueFrom: 
            configMapKeyRef:
              name: envconfigmap
              key: PROXY_OPENID_AUTH_URL
        - name: PROXY_OPENID_JWKS_URL
          valueFrom: 
            configMapKeyRef:
              name: envconfigmap
              key: PROXY_OPENID_JWKS_URL
        - name: PROXY_OPENID_TOKEN_URL
          valueFrom: 
            configMapKeyRef:
              name: envconfigmap
              key: PROXY_OPENID_TOKEN_URL
        - name: PROXY_OPENID_USERINFO_URL
          valueFrom: 
            configMapKeyRef:
              name: envconfigmap
              key: PROXY_OPENID_USERINFO_URL
        - name: PROXY_OPENID_CLIENT_ID
          valueFrom: 
            configMapKeyRef:
              name: envconfigmap
              key: PROXY_OPENID_CLIENT_ID
        - name: PROXY_OPENID_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: openidsecret
              key: PROXY_OPENID_CLIENT_SECRET
        - name: PROXY_OPENID_USERNAME_CLAIM
          valueFrom: 
            configMapKeyRef:
              name: envconfigmap
              key: PROXY_OPENID_USERNAME_CLAIM
```

This is working very fine 👍 ✅
